API_SERVICE_NAME = "youtube"
API_VERSION = "v3"
YOUTUBE_API_KEY='AIzaSyBstqZbUjsTInCR1kMpSoLBPhF0kOUNOY0'
OPENAI_API_KEY='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'
GEMINI_API_KEY='AIzaSyAQYXlMu5D0kzMR5ppFkhUIelhCzqfeMUs'
TWITTER_API_KEY = "qDa4QtXxGg9VbSBC7JDyNz2Xu"
TWITTER_API_KEY_SECRET = "q03FiRuwLyfykvwZX4RpwjD4mXFF8dQtFxmI8rLp1fEJjWAdx3"
TWITTER_ACCESS_TOKEN = "1863544394311168000-LueEm9vYihojjw8201rM12za5ohvby"
TWITTER_ACCESS_TOKEN_SECRET = "hfUGOk66QOdwzIliGIusZKPoKJFM7iaFaWREr5MRrULLu"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAIpAxQEAAAAARmsnIigHIL6qoPA%2FEDGKJOS4veU%3D11mG9NRZN3KE6Caq3FWafm6wX9zRxvCxQD1FOvY2tpfqHks0IF"
