API_SERVICE_NAME = "youtube"
API_VERSION = "v3"
YOUTUBE_API_KEY='AIzaSyBstqZbUjsTInCR1kMpSoLBPhF0kOUNOY0'
OPENAI_API_KEY='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'
GEMINI_API_KEY='AIzaSyAQYXlMu5D0kzMR5ppFkhUIelhCzqfeMUs'
TWITTER_API_KEY = "HXEd1lgZLkrIKDAulgDmQKAOQ"
TWITTER_API_KEY_SECRET = "juyX65PR9zPvIhS2653vsjlSBL8KPpUj2jLFfXfXt2w9oO3xZG"
TWITTER_ACCESS_TOKEN = "1863544394311168000-33egNwSDDAkwKHJUdQIHKevKd3jqqo"
TWITTER_ACCESS_TOKEN_SECRET = "pQw1tyuvyu4W4pF14At915UckZcgRn75RN690m9CtXROm"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAIpAxQEAAAAA3KZiDCMC2o%2FCfbrthVUOb9eiqGQ%3DDCcVNcpQL1aBUndWgplCGlVUfBW9mNEYtpnUkVPG9VCaShbVSj"
FACEBOOK_ACCESS_TOKEN = "EAAP2jbgg3VIBOzaOsZCbFZACZA7vwhruVVAYzre10y0BU1vuIHd13lzuuTKFDFJqs3DLnSz0ZAjuyNyC0jEaIaSOgClgo9J3DRTjZCiGEvDhHcgaZC44k5O3Vuw1BRskZBlyJaEWMD5de1ErJEw99zTsSrseb2B1ZAN9UqtJAdCOZCKxdIp2Bc9T7zslWshjTaihZAbzSIlpnnS56Hklyqk7zgwHHle53qSoonYGgZD"
FACEBOOK_API_VERSION = "v21.0"
