API_SERVICE_NAME = "youtube"
API_VERSION = "v3"
YOUTUBE_API_KEY='AIzaSyBstqZbUjsTInCR1kMpSoLBPhF0kOUNOY0'
OPENAI_API_KEY='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'
GEMINI_API_KEY='AIzaSyAQYXlMu5D0kzMR5ppFkhUIelhCzqfeMUs'
TWITTER_API_KEY = "zWMsIMEVsiboxVoRveMBacICq"
TWITTER_API_KEY_SECRET = "vKIUkZRVEN6jyqZ4Xh2AiUDyoeq5Ss4eglY6I7mIFm5HMfFtFJ"
TWITTER_ACCESS_TOKEN = "1591108525513617413-kIx9aEqCGn8PyBCYcOAuMtwWpXcXKW"
TWITTER_ACCESS_TOKEN_SECRET = "gUPJiF16E4Jothjz6yJZWfjSEYm0qWGziSP9I7rhoM6tl"
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAANctxQEAAAAAM%2FkvMnFULF1Df4OcH69YewuPZJA%3Ds6Rw4chjSgPGf9kkkC9zjdRkluI5ZmQNNHFIM0t7LSSdVJB889"  
